Update pipeline.yaml

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -18,12 +18,17 @@ jobs:
     runs-on: ubuntu-latest
     if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'prod' && startsWith(github.ref, 'refs/tags/')
     steps:
-      # Checkout the repository
       - name: Checkout code
         uses: actions/checkout@v4
         
-      - name: Print
-        run: echo "JOB RUNNING......"
+      - name: Validate tag name
+        run: |
+          if [[ "${{ github.ref_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Tag ${{ github.ref_name }} is valid for PROD deployment"
+          else
+            echo "Error: Tag name ${{ github.ref_name }} does not match vX.X.X format."
+            exit 1
+          fi
 
       # Extract metadata (branch, commit, version)
       # - name: Extract metadata
